title: Deepheat Blues Band
logo: http://assets/img/IMG_8777_edited.jpg
description: Deepheat Blues Band is a band for the misfits of the current climate.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
